// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function NoneFooterNavigationLayout({ children }) {
  return <main className="">{children}</main>;
}
