// 1000단위 콤마 처리
export function formatCommaNumber(number) {
  if (isNaN(number)) return number; // 숫자가 아니면 그대로 반환
  return number.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
}

// 카테고리 리스트
export const categories = [
  { key: 12, name: '관광지' },
  { key: 14, name: '문화시설' },
  { key: 15, name: '행사/공연/축제' },
  { key: 28, name: '레포츠' },
  { key: 32, name: '숙박' },
  { key: 38, name: '쇼핑' },
  { key: 39, name: '음식점' },
];

// 소개정보조회 카테고리 마다 오브젝트 이름 key value 로 묶음
export const introCategorizedFields = {
  12: [
    // 관광지
    { key: 'accomcount', name: '수용인원' },
    { key: 'chkcreditcard', name: '신용카드 가능 여부' },
    { key: 'expagerange', name: '체험 가능 연령' },
    { key: 'expguide', name: '체험 안내' },
    { key: 'heritage1', name: '세계 문화유산 유무' },
    { key: 'heritage2', name: '세계 자연유산 유무' },
    { key: 'heritage3', name: '세계 기록유산 유무' },
    { key: 'infocenter', name: '문의 및 안내' },
    { key: 'opendate', name: '개장일' },
    { key: 'parking', name: '주차시설' },
    { key: 'restdate', name: '쉬는 날' },
    { key: 'useseason', name: '이용 시기' },
    { key: 'usetime', name: '이용 시간' },
  ],
  14: [
    // 문화시설
    { key: 'accomcountculture', name: '수용인원' },
    { key: 'chkcreditcardculture', name: '신용카드 가능 여부' },
    { key: 'discountinfo', name: '할인 정보' },
    { key: 'infocenterculture', name: '문의 및 안내' },
    { key: 'parkingculture', name: '주차시설' },
    { key: 'parkingfee', name: '주차 요금' },
    { key: 'restdateculture', name: '쉬는 날' },
    { key: 'usefee', name: '이용 요금' },
    { key: 'usetimeculture', name: '이용 시간' },
    { key: 'scale', name: '규모' },
    { key: 'spendtime', name: '관람 소요 시간' },
  ],
  15: [
    // 행사/공연/축제
    { key: 'agelimit', name: '관람 가능연령' },
    { key: 'bookingplace', name: '예매처' },
    { key: 'discountinfofestival', name: '할인 정보' },
    { key: 'eventenddate', name: '행사 종료일' },
    { key: 'eventhomepage', name: '행사 홈페이지' },
    { key: 'eventplace', name: '행사 장소' },
    { key: 'eventstartdate', name: '행사 시작일' },
    { key: 'festivalgrade', name: '축제 등급' },
    { key: 'placeinfo', name: '행사장 위치안내' },
    { key: 'playtime', name: '공연시간' },
    { key: 'program', name: '행사 프로그램' },
    { key: 'spendtimefestival', name: '관람 소요시간' },
    { key: 'sponsor1', name: '주최자 정보' },
    { key: 'sponsor1tel', name: '주최자 연락처' },
    { key: 'sponsor2', name: '주관사 정보' },
    { key: 'sponsor2tel', name: '주관사 연락처' },
    { key: 'subevent', name: '부대 행사' },
    { key: 'usetimefestival', name: '이용요금' },
  ],
  28: [
    // 레포츠
    { key: 'accomcountleports', name: '수용인원' },
    { key: 'chkcreditcardleports', name: '신용카드 가능 여부' },
    { key: 'expagerangeleports', name: '체험 가능 연령' },
    { key: 'infocenterleports', name: '문의 및 안내' },
    { key: 'openperiod', name: '개장 기간' },
    { key: 'parkingfeeleports', name: '주차 요금' },
    { key: 'parkingleports', name: '주차시설' },
    { key: 'reservation', name: '예약 안내' },
    { key: 'restdateleports', name: '쉬는날' },
    { key: 'scaleleports', name: '규모' },
    { key: 'usefeeleports', name: '입장료' },
    { key: 'usetimeleports', name: '이용 시간' },
  ],
  32: [
    // 숙박
    { key: 'accomcountlodging', name: '수용 가능 인원' },
    { key: 'benikia', name: '베니키아 여부' },
    { key: 'checkintime', name: '입실 시간' },
    { key: 'checkouttime', name: '퇴실 시간' },
    { key: 'chkcooking', name: '객실 내 취사 여부' },
    { key: 'foodplace', name: '식음료장' },
    { key: 'goodstay', name: '굿스테이 여부' },
    { key: 'hanok', name: '한옥 여부' },
    { key: 'infocenterlodging', name: '문의 및 안내' },
    { key: 'parkinglodging', name: '주차시설' },
    { key: 'pickup', name: '픽업 서비스' },
    { key: 'roomcount', name: '객실 수' },
    { key: 'reservationlodging', name: '예약 안내' },
    { key: 'reservationurl', name: '예약 안내 홈페이지' },
    { key: 'roomtype', name: '객실 유형' },
    { key: 'scalelodging', name: '규모' },
    { key: 'subfacility', name: '부대시설' },
    { key: 'barbecue', name: '바비큐장 여부' },
    { key: 'beauty', name: '뷰티시설 정보' },
    { key: 'beverage', name: '식음료장 여부' },
    { key: 'bicycle', name: '자전거 대여 여부' },
    { key: 'campfire', name: '캠프파이어 여부' },
    { key: 'karaoke', name: '노래방 여부' },
    { key: 'seminar', name: '세미나실 여부' },
    { key: 'sports', name: '스포츠 시설 여부' },
    { key: 'refundregulation', name: '환불 규정' },
    { key: 'publicbath', name: '공용 샤워실 여부' },
    { key: 'publicpc', name: '공용 PC실 여부' },
    { key: 'sauna', name: '사우나실 여부' },
    { key: 'fitness', name: '휘트니스 센터 여부' },
  ],
  38: [
    // 쇼핑
    { key: 'fairday', name: '장서는 날' },
    { key: 'infocentershopping', name: '문의 및 안내' },
    { key: 'opendateshopping', name: '개장일' },
    { key: 'opentime', name: '영업시간' },
    { key: 'parkingshopping', name: '주차시설' },
    { key: 'restdateshopping', name: '쉬는 날' },
    { key: 'restroom', name: '화장실 설명' },
    { key: 'saleitem', name: '판매 품목' },
    { key: 'saleitemcost', name: '판매 품목별 가격' },
    { key: 'scaleshopping', name: '규모' },
    { key: 'shopguide', name: '매장 안내' },
    { key: 'chkcreditcardshopping', name: '신용카드 가능 여부' },
    { key: 'culturecenter', name: '문화센터 바로가기' },
  ],
  39: [
    // 음식점
    { key: 'lcnsno', name: '인허가 번호' },
    { key: 'chkcreditcardfood', name: '신용카드 가능 여부' },
    { key: 'discountinfofood', name: '할인 정보' },
    { key: 'firstmenu', name: '대표 메뉴' },
    { key: 'infocenterfood', name: '문의 및 안내' },
    { key: 'kidsfacility', name: '어린이 놀이방' },
    { key: 'opendatefood', name: '개업일' },
    { key: 'opentimefood', name: '영업시간' },
    { key: 'packing', name: '포장 가능 여부' },
    { key: 'parkingfood', name: '주차시설' },
    { key: 'reservationfood', name: '예약 안내' },
    { key: 'restdatefood', name: '쉬는 날' },
    { key: 'scalefood', name: '규모' },
    { key: 'seat', name: '좌석 수' },
    { key: 'smoking', name: '금연/흡연 여부' },
    { key: 'treatmenu', name: '취급 메뉴' },
  ],
};
