// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function AuthLayout({ children }) {
  return (
    <div>
      인증화면 들어갈 레이아웃
      {children}
    </div>
  );
}
